# Please note that after a release is created (for example, `nvfp/now-i-can-sleep@1.0.0`),
# any changes made to the repository will not be reflected in that version (i.e., if users
# use version `1.0.0`, the changes will not be present).  ~Nicholas@20230717


name: "Not GitHub Actions, just experimental."
description: "For testing and experimental purposes."
author: "NVfastplease"
branding:
  icon: alert-triangle
  color: orange

inputs:
  load:
    description: abc
    required: true
  dock:
    description: xyz
    required: true
  git-name:
    description: xyz
    required: true
  git-email:
    description: xyz
    required: true
  gh-repo-name:
    description: xyz
    required: true
  container:
    description: xyz
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.8

    - name: Set script permissions
      shell: bash
      run: find $GITHUB_ACTION_PATH/nics-compiler/workflows -type f -name "*.sh" -exec chmod +x {} \;
    
    - name: Checkout Load branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.load }}
    
    - name: Set up NICS working directory
      shell: bash
      env:
        GH_REPO_NAME: ${{ inputs.gh-repo-name }}
        CONTAINER: ${{ inputs.container }}
      run: $GITHUB_ACTION_PATH/nics-compiler/workflows/setup-working-dir.sh

    # - name: Checkout Dock branch
    #   uses: actions/checkout@v3
    #   with:
    #     ref: ${{ inputs.dock }}

    # - name: Compile
    #   shell: bash
    #   run: $GITHUB_ACTION_PATH/nics-compiler/workflows/compile.sh

    # - name: Deploy
    #   shell: bash
    #   run: $GITHUB_ACTION_PATH/nics-compiler/workflows/deploy.sh