name: "Not GitHub Actions, just experimental."
description: "For testing and experimental purposes."
author: "NVfastplease"
branding:
  icon: alert-triangle
  color: orange

inputs:
  foo:
    description: abc
    required: true
  bar:
    description: xyz
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.8

    - name: Set script permissions
      shell: bash
      run: find $GITHUB_ACTION_PATH/nics-compiler/workflows -type f -name "*.sh" -exec chmod +x {} \;
    
    - name: Checkout Load branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up NICS working directory
      shell: bash
      env:
        TESTFOO: ${{ inputs.foo }}
      run: $GITHUB_ACTION_PATH/nics-compiler/workflows/setup-working-dir.sh

    - name: Checkout Dock branch
      uses: actions/checkout@v3
      with:
        ref: mocking-nics-workflow

    - name: Compile
      shell: bash
      run: $GITHUB_ACTION_PATH/nics-compiler/workflows/compile.sh

    - name: Deploy
      shell: bash
      run: $GITHUB_ACTION_PATH/nics-compiler/workflows/deploy.sh