name: "Not GitHub Actions, just experimental."
description: "For testing and experimental purposes."
author: "NVfastplease"
branding:
  icon: alert-triangle
  color: orange

inputs:
  # 

runs:
  using: 'composite'
  steps:
    - name: foo
      shell: bash
      env:
        foo: ${{ inputs.foo }}
      run: $GITHUB_ACTION_PATH/foo
