name: "Not GitHub Actions, just experimental."
description: "For testing and experimental purposes."
author: "NVfastplease"
branding:
  icon: alert-triangle
  color: orange

inputs:
  foo:
    description: abc
    required: true
  bar:
    description: xyz
    required: true

runs:
  using: 'composite'
  steps:      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Foo
      shell: bash
      run: |
        echo "CWD foo: '$(pwd)'"
        echo "---"
        ls

    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Foo
      shell: bash
      run: |
        echo "::group:: Title 1"
        echo "CWD bar: '$(pwd)'"
        echo "---"
        ls
        echo "::endgroup::"

    - shell: bash
      env:
        NICS_VERSION: ${{ inputs.foo }}
        BAR: ${{ inputs.bar }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/dir/prepare.sh
        $GITHUB_ACTION_PATH/dir/prepare.sh

        chmod +x $GITHUB_ACTION_PATH/dir/main.sh
        $GITHUB_ACTION_PATH/dir/main.sh